### ISSUE TITLE
thirdparty中无法集成gevent

### ISSUE THREAD

**Issue by JaySon-Huang** [fooying/3102#35]
gevent库需要编译为.so库进行调用，单纯地把gevent放到thirdparty中，跨平台的时候会出现问题。  
比如目前版本`a04fd533358cfb996c02a60560f767adbfe0f8f6`,导入thirdparty中的gevent时在我的Mac OS X上会报错，要删除thirdparty中的gevent重新用`pip`编译安装，修改导入语句之后才能使用

**Comment by fooying** [comment]
@JaySon-Huang 你新提交的代码也可以解决这个问题吗？

**Comment by fooying** [comment]
我考虑集成三份gevent目录，分别在linux、mac和windows的三种环境，然后在**init**.py里判断系统import不同的文件，看看可不可行

**Comment by JaySon-Huang** [comment]
我不知道怎样处理O,O, @fooying 你来吧

**Comment by fooying** [comment]
尝试了下，那样处理各种奇葩
准备把3102持续集成和make安装的搞起来
这样使用前只要make下就可以
如果实在连make都不会的，那就没办法了
