### ISSUE TITLE
存活检测

### ISSUE THREAD

**Issue by fooying** [fooying/3102#4]
增加存活检测功能
在fuzzing完成后对结果进行存活检测

**Comment by flsf** [comment]
1.加一个开关参数,默认不检测存活,如何?
2.是用code 200 来检测,还是拿titile呢.要不要做两个级别...

**Comment by fooying** [comment]
嗯，就是增加一个开关，然后默认不检测
我的想法是做完整get请求，返回code，如果有titile返回titile
这样可以根据title直接判断对应系统类型

**Comment by flsf** [comment]
增加了返回code,自动适配输出(csv,html),明天弄title
