### ISSUE TITLE
默认配置不一致导致bug

### ISSUE THREAD

**Issue by JaySon-Huang** [fooying/3102#55]
刚刚merge了[最近版本](https://github.com/fooying/3102/commit/b6dfc7f477c04e5d0c6291f29c782538473d5d32)的代码，然后出现异常无法运行了。
![screen shot 2015-03-03 at 16 07 22](https://cloud.githubusercontent.com/assets/4865550/6458577/0e8c640c-c1c0-11e4-9d54-455855543fd6.png)

中间有几行是我print一些变量来查看原因。

出现异常的原因是读取`3102.conf`文件中配置的值为空，然后执行int进行转换的时候出现`ValueError`了。

**Comment by flsf** [comment]
恩,是的,昨天已经提交修复了

**Comment by JaySon-Huang** [comment]
我觉得这样修改有几个地方不妥。
- `run3102.py`里面是先执行解析命令行参数，再通过`initOptions`来读取`3102.conf`中的配置:
  
  ```
  cmdLineOptions.update(parse().__dict__)
  initOptions(cmdLineOptions)
  start()
  ```

而`options.py`中写成

```
         if mergeOption:
            if option == 'plugins_specific':
                mergeOption = mergeOption.split()
            elif option in ('max_level', 'pool_size', 'timeout', 'log_level'):
                mergeOption = int(mergeOption)

             inputOptions[option] = mergeOption
```

这样只是避免了ValueError的产生，但是如果`3102.conf`中的值不为空的话，那么命令行传入的参数就会因为最后一行而被`3102.conf`中的配置覆盖了，命令行参数就没有意义了。  

我的理解是，`3102.conf`中存储的是默认配置。而程序运行时应该先读取`3102.conf`中的默认配置，然后再解析命令行参数，根据命令行参数update字典吧？

<hr />
- `utils.py`中的`checkFile`函数抛出了异常，但是在`options.py`中使用的时候没有处理异常。其实我觉得这里没有必要使用异常，返回布尔值，然后调用的时候判断返回值就好了。

**Comment by flsf** [comment]
你的意思是命令行参数的优先级弄高?

**Comment by flsf** [comment]
说的很有道理

**Comment by flsf** [comment]
你说的checkFile问题,如果不能读 checkFile就直接抛出异常,程序退出了
