### ISSUE TITLE
关于paths.output_file

### ISSUE THREAD

**Issue by JaySon-Huang** [fooying/3102#59]
paths.output_file应该是用于存储输出路径的。

而现在的代码中只是在 3102/core/controllers/controller.py中赋值了命令行的参数，然后作为初始化参数初始化Output类。
真正的存储路径在Output类中可能会发生变化(__get_output_file函数中)，这样paths.output_file的值就不是存储输出路径

现在的paths.output_file变量仅仅是作为cmdLineOptions.output_file的一个副本

修改方式（三种选一）：
- 暂时取消paths.output_file，初始化Output的时候使用cmdLineOptions中的值。而且暂时也没有其他地方需要使用输出路径。
- 在Output类中确定了输出路径之后再赋值paths.output_file
- 把确定输出路径的部分独立出来

**Comment by flsf** [comment]
那就paths.output_file删掉吧,没什么用,之后用了再说好了,你看着改吧,这个又不涉及大范围的删改,无所谓
